# Generated by Django 5.2.6 on 2025-09-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
                ('points', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('address', models.JSONField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('highlight', models.JSONField()),
                ('subtitle', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
                ('image_url', models.CharField(max_length=255)),
                ('expert_areas', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.JSONField()),
                ('link', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='core.hero')),
            ],
        ),
    ]
